default_language_version:
    python: python3.8

default_stages: [commit, push]

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        types: [python]
        language: system
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        types: [python]
        language: system
        args:
          - "--max-line-length=88"
          - "--ignore=E203"
